language: csharp
solution: "./TDD.Kata.StringCalculator/TDD.Kata.StringCalculator.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./TDD.Kata.StringCalculator/TDD.Kata.StringCalculator.sln
script:
- xbuild ./Fibonacci/Fibonacci.sln
- mono ./Fibonacci/packages/xunit.runner.console*/tools/xunit.console.exe ./TDD.Kata.StringCalculator/TDD.Kata.StringCalculator.Tests.Unit/bin/Debug/TDD.Kata.StringCalculator.Tests.Unit.dll
